version: '3.8'

services:
  db:
    image: postgres:16.0
    env_file:
      - ./.env
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - db-networks

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    env_file:
      - ./.env

    depends_on:
      - db

    networks:
      - db-networks

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/back
    depends_on:
      - db

    networks:
      - db-networks

    env_file:
      - ./.env
    restart: on-failure

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1980:1980
    volumes:
      - ./frontend:/front

volumes:
  db-volume:

networks:
  db-networks:
    driver: bridge
