apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # generic type for generating secret key-value pair
             # you can have more complex type such as type with tls certificate
data:
  mongo-user: YXBw # base 64 encoded (app)
  mongo-password: MTIzNA== # base 64 encoded (1234) 
  
# to generate a base64 encoding type the following line in the terminal
# echo -n 'value' | base64